server:
  port: 8082
  shutdown: graceful

spring:
  application:
    name: order-processor-service

  main:
    banner-mode: off

  kafka:
    bootstrap-servers: localhost:9092
    security:
      protocol: PLAINTEXT
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
      enable-auto-commit: true
      properties:
        spring.json.trusted.packages: '*'
        spring.json.use.type.headers: false
        partition.assignment.strategy: org.apache.kafka.clients.consumer.CooperativeStickyAssignor
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 30

kafka:
  order-request:
    topic: example-order_taker_service-order_request-dev
    concurrency: 3
  order-result:
    topic: example-order_processor_service-order_result-dev

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org.zalando.logbook: trace